name: Release new version

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Select the release type
        required: true
        options:
          - major
          - patch
          - minor

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release new version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required to get all existing tags
          fetch-tags: true

      - name: Stop if there are no new changes
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --always)
          LAST_COMMIT=$(git rev-parse HEAD)
          LASTEST_TAG_COMMIT=$(git rev-list -n 1 $LATEST_TAG)
          if [ "$LASTEST_TAG_COMMIT" == "$LAST_COMMIT" ]; then
            echo "No new changes since the last tag. Stopping the workflow."
            exit 1
          fi
          exit 0

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Create new version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          npm version ${{ github.event.inputs.release-type }} -m "chore: v%s"

      - name: Build project
        run: |
          npm run build

      - name: Publish new version
        run: |
          git push --follow-tags
          npm publish
