name: Release new version

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Select the release type
        required: true
        options:
          - major
          - patch
          - minor

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release new version

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Required to get all existing tags
          fetch-tags: true

      - name: Stop if there are no new changes
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --always)
          LAST_COMMIT=$(git rev-parse HEAD)
          LASTEST_TAG_COMMIT=$(git rev-list -n 1 $LATEST_TAG)
          if [ "$LASTEST_TAG_COMMIT" == "$LAST_COMMIT" ]; then
            echo "No new changes since the last tag. Stopping the workflow."
            exit 1
          fi
          exit 0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Create new version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          pnpm version ${{ github.event.inputs.release-type }} --message "chore: v%s"

      - name: Build project
        run: |
          pnpm run build

      - name: Publish new version
        run: |
          git push --follow-tags
          pnpm stage publish
